name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
            fontconfig    \
            imagemagick   \
            libgeos++-dev \
            libproj-dev   \
            poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
      - name: Install Tex Live
        run: |
          pip install latex
          sudo apt-get install dvipng
          sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
      - name: Refresh README.md
        run: |
          python make_readme.py > README.md
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add .
          git commit -m "Create diagram and make refresh README"
          git push